<a href="https://colab.research.google.com/github/wqiu96/MA574_Portfolio-Valuation-and-Risk-Management/blob/master/src/report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.linalg import *
import os

In [2]:
!git clone https://github.com/wqiu96/MA574_Portfolio-Valuation-and-Risk-Management.git

Cloning into 'MA574_Portfolio-Valuation-and-Risk-Management'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 790 (delta 0), reused 0 (delta 0), pack-reused 764
Receiving objects: 100% (790/790), 3.70 MiB | 5.59 MiB/s, done.
Resolving deltas: 100% (355/355), done.


In [3]:
cd MA574_Portfolio-Valuation-and-Risk-Management/src/project3/report/

/content/MA574_Portfolio-Valuation-and-Risk-Management/src/project3/report


In [0]:
os.chdir('/content/MA574_Portfolio-Valuation-and-Risk-Management/src/project3/report')
file_chdir = os.getcwd()
filecsv_list = []
for root,dirs,files in os.walk(file_chdir):
  for file in files:
    if os.path.splitext(file)[1] == '.csv':
      filecsv_list.append(file)
R = pd.DataFrame()
for csv in filecsv_list:
  data = pd.read_csv(csv)
  R[csv.strip('.csv')] = data['Adj Close']


In [0]:
week1 = np.array([[   2620.41838146],[   2899.10478588],[  17122.98774791],[  -1166.27789306],[  37710.71208477],[  -4781.55759772],[  20750.36868562],[ 115687.12463153],[  26118.58851702],[-110907.4472778 ],[  44884.05409239],[ -11237.74966272],[  46278.73136243],[  34435.7300208 ],[ 137918.77048575],[ 146737.38625926],[  -1166.27789306],[    773.79443426],[   1171.78854958],[ -42774.04808203],[  37830.01590757]])
week2 = np.array([[ -36154.11390515],[   3088.34259836],[  18575.43903261],[  11397.6580713 ],[  28022.3340708 ],[  13561.79727925],[ -18091.61522142],[   2345.5690904 ],[ -13279.49295108],[-250137.57844129],[  39541.52258879],[ -13207.79962763],[  52942.06253231],[ -13550.83530922],[ 171820.57024838],[ 137446.40918201],[ 135456.02263072],[   2089.1278969 ],[  44454.84682613],[ 129705.56054477],[  53974.17286306]])
week3 = np.array([[ -45484.7637217 ],[   -679.65829001],[  19876.53562296],[ -14756.5210627 ],[  91735.99961269],[  24805.00600562],[  -7877.93386978],[ -23168.61448209],[  -3268.35591659],[-275347.659066  ],[  49816.22058929],[  14182.03256549],[  74396.28929161],[ -18741.14392497],[ 133437.13752936],[ 123402.03224969],[ 124660.47384134],[  17739.67401901],[  49078.39468121],[ 109415.74988416],[  56779.10444144]])
week4 = np.array([[ -23136.82968596],[ -22976.28840536],[  20244.61700118],[ -13275.41108797],[  83177.85411232],[  16444.4423524 ],[  -2431.17157459],[ -19394.62058874],[  -3587.732925  ],[-236576.02346441],[  55717.49264295],[  18877.38085054],[  96090.93658475],[ -25808.09727977],[ 165423.05162546],[ 151039.14519686],[  93779.39522804],[  21210.90583318],[  21492.41881251],[  46555.49404597],[  57133.04072566]])
week5 = np.array([[  -9960.15340479],[ -36423.97152479],[  10700.8065328 ],[  -1266.14901731],[  81874.01694402],[  15825.36127658],[   8310.48399868],[ -25009.21241495],[  -5107.24234546],[-297735.79134959],[  53095.56975296],[  19961.17958912],[ 106473.2329959 ],[  -6590.09333768],[ 169132.05094267],[ 128432.38161741],[ 117956.18073249],[  30306.09280769],[  45316.97077624],[  34982.86525729],[  59725.42017073]])
week_index = [0,5,10,15,19,24]
leverage = np.array([1.6917583037848998,2.37768574182317,2.5572986013353995,2.388744700047198,2.528370453578312])

In [35]:
np.array([2,2,3,4,5])/np.array([2,2,3,4,5])

array([1., 1., 1., 1., 1.])

In [54]:
np.array(R.iloc[0])

array([  36.290001,  140.559998,   93.976875,  196.479996,  194.720001,
        132.919998,   59.869999,  117.045006,  187.458649, 1291.369995,
         52.746006,   92.093765,  119.07    ,  129.698822,   37.790001,
        256.729218,  217.979996,   32.224075,   18.9     ,  179.690002,
        128.820007])

array([2620.41838146])

In [21]:
R['GOOG'][0:4]
lambda week1/

0    1291.369995
1    1292.030029
2    1291.800049
3    1308.859985
Name: GOOG, dtype: float64

In [0]:
for i in range(len(filecsv_list)):
  